name: 🗳 Installing Apache
on: workflow_call
jobs:
  install_apache_job:
    runs-on: self-hosted
    steps:
    - name: ssh into vm
      run: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u ubuntu -i /home/ubuntu/runner/_work/ansible-githubCI/ansible-githubCI/host_inventory /home/ubuntu/runner/_work/ansible-githubCI/ansible-githubCI/playbooks/apache-install.yml 
